function summary = run_quadtree_smoke_validation(mesh_file, output_directory)
%RUN_QUADTREE_SMOKE_VALIDATION Exercise 90/180/360 m conservative routing.

arguments
    mesh_file (1,:) char
    output_directory (1,:) char = fullfile(tempdir,'hydropol2d-quadtree-smoke')
end
config=struct('duration_s',600,'output_interval_s',60, ...
    'routing_solver','local_inertial','surface_roughness',0.05, ...
    'courant',0.2,'min_dt_s',0.01,'max_dt_s',10, ...
    'critical_flow',true,'hydrology_enabled',false,'groundwater_enabled',false);
forcing=struct('surface_source_m_s',1e-5);
case_definition=struct('mesh_file',mesh_file,'fine_resolution_m',90, ...
    'coarse_resolution_m',360,'urban_refinement_buffer_m',120, ...
    'config',config,'forcing',forcing,'output_prefix','quadtree-smoke', ...
    'maximum_mass_residual_fraction',1e-8);
results=HydroPol2D_Run_Quadtree_Case(case_definition,output_directory,false);
summary=results.summary;
assert(summary.passed && summary.maximum_mass_residual_fraction<=1e-8, ...
    'HydroPol2D:QuadtreeValidation','Quadtree smoke validation failed.');
end
