function Summary = run_voronoi_vtilted_end_to_end_validation(mesh_directory,output_directory)
%RUN_VORONOI_VTILTED_END_TO_END_VALIDATION Full hydrology/GW/output slice.

arguments
    mesh_directory (1,:) char
    output_directory (1,:) char
end
root=fullfile(fileparts(mfilename('fullpath')),'..','..');
addpath(fullfile(root,'HydroPol2D_Functions'));
if exist(output_directory,'dir')~=7, mkdir(output_directory); end

mesh_file=fullfile(mesh_directory,'vtilted-variable-mesh.nc');
overlap_file=fullfile(mesh_directory,'vtilted-variable-overlap.nc');
mesh=HydroPol2D_Read_UGRID(mesh_file);
outlet=find(mesh.edge_neighbor==0 & abs(mesh.edge_midpoint_y)<1e-8 & ...
    mesh.edge_midpoint_x>=380 & mesh.edge_midpoint_x<=440);
assert(abs(sum(mesh.edge_length(outlet))-60)<=1e-8, ...
    'HydroPol2D:VoronoiValidation','V-tilted outlet width must be 60 m.');

hydrology=struct('hru_fraction',repmat([0.65 0.35],mesh.n_cells,1), ...
    'pervious_fraction',[1 0.25],'lai',[3 0],'crop_coefficient',[1 0.4], ...
    'soil_depth_m',[2 1.2],'root_depth_m',[1 0.3], ...
    'theta_r',[0.05 0.07],'theta_sat',[0.45 0.42], ...
    'alpha_vg_1_m',[3.6 1.9],'n_vg',[1.56 1.31], ...
    'ksat_m_s',[5e-6 5e-7],'initial_soil_saturation',[0.35 0.45], ...
    'wilting_saturation',[0.10 0.15],'capillary_rise_enabled',true);
config=struct('duration_s',6*3600,'min_dt_s',0.01,'max_dt_s',30, ...
    'output_interval_s',600,'surface_roughness',0.04,'courant',0.2, ...
    'hydrology_enabled',true,'hydrology',hydrology,'groundwater_enabled',true, ...
    'initial_groundwater_head_m',mesh.surface_bed-2, ...
    'aquifer_bottom_m',mesh.surface_bed-10,'hydraulic_conductivity_m_s',1e-5, ...
    'specific_yield',0.2,'groundwater_update_interval_s',600, ...
    'riverbed_hydraulic_conductivity_m_s',1e-8,'riverbed_thickness_m',0.5);
config.gauges=struct('name','outlet_edge','edge_id',outlet(1),'sign',1);
rain_rate=30e-3/3600; rain_duration=3*3600;
forcing=struct('surface_source_m_s',@(time_s,state,current_mesh) ...
    double(time_s<rain_duration)*rain_rate, ...
    'meteorology',struct('temperature_c',25,'maximum_temperature_c',30, ...
    'minimum_temperature_c',20,'day_of_year',200,'latitude_deg',20, ...
    'wind_speed_m_s',2,'relative_humidity_pct',60,'krs',0.16,'albedo',0.23), ...
    'surface_boundary',struct('edge_id',outlet,'type',"normal_flow",'value',0.004));
options=struct('background_target_width_m',40,'minimum_cell_width_m',20, ...
    'maximum_adjacent_size_ratio',2,'urban_target_width_m',20, ...
    'urban_transition_buffer_m',0, ...
    'unresolved_river_policy','neal_subgrid');
VoronoiCase=struct('mesh_file',mesh_file,'overlap_file',overlap_file, ...
    'config',config,'forcing',forcing,'options',options, ...
    'output_prefix','vtilted-variable-end-to-end', ...
    'expected_input_volume_m3',rain_rate*rain_duration*sum(mesh.cell_area), ...
    'maximum_input_volume_error_fraction',1e-10, ...
    'maximum_mass_residual_fraction',1e-3);
VoronoiCase.output_controls=struct('native_output_interval_s',600, ...
    'raster_stack_interval_s',3600,'write_videos',true);
case_file=fullfile(output_directory,'vtilted-variable-case.mat');
save(case_file,'VoronoiCase');
prepared=load(case_file,'VoronoiCase');
results=HydroPol2D_Run_Voronoi_Case(prepared.VoronoiCase,output_directory,true);

required_variables={'surface_depth_face_m','surface_velocity_face_m_s','soil_water_m_face', ...
    'cumulative_infiltration_m_face','cumulative_actual_et_m_face','groundwater_head_face_m', ...
    'groundwater_depth_face_m','groundwater_river_exchange_face_m_s', ...
    'surface_depth_map_m','map_time_s','row','column'};
variables=string({ncinfo(results.output_netcdf).Variables.Name});
assert(all(ismember(required_variables,variables)), ...
    'HydroPol2D:VoronoiValidation','End-to-end NetCDF is missing required states.');
assert(numel(results.raster_files)>=10 && all(isfile(results.raster_files)), ...
    'HydroPol2D:VoronoiValidation','End-to-end raster post-processing is incomplete.');
assert(isfile(fullfile(output_directory,'Modeling_Results','Figures_PNG','State_Summary.png')), ...
    'HydroPol2D:VoronoiValidation','End-to-end state summary figure is missing.');
assert(isfile(fullfile(output_directory,'Modeling_Results','Figures_PDF','State_Summary.pdf')) && ...
    isfile(fullfile(output_directory,'Modeling_Results','Figures_SVG','State_Summary.svg')), ...
    'HydroPol2D:VoronoiValidation','End-to-end vector summary figures are missing.');
assert(isfile(fullfile(output_directory,'Modeling_Results','GIFs_MP4','Standard_Multipanel.mp4')), ...
    'HydroPol2D:VoronoiValidation','End-to-end standard video is missing.');
assert(isfile(fullfile(output_directory,'Modeling_Results','Tables_CSV','Water_Balance.csv')) && ...
    isfile(fullfile(output_directory,'Modeling_Results','Manifests','temporal_rasters.csv')), ...
    'HydroPol2D:VoronoiValidation','End-to-end table or temporal manifest is missing.');
assert(isfile(fullfile(output_directory,'Modeling_Results','Tables_CSV','Gauge_Hydrographs.csv')), ...
    'HydroPol2D:VoronoiValidation','Configured-gauge hydrograph is missing.');

native_time=double(ncread(results.output_netcdf,'time_s'));
gauge_q=double(ncread(results.output_netcdf,'gauge_discharge_m3_s'));
edge_q=double(ncread(results.output_netcdf,'edge_discharge_per_width_m2_s'));
reference_q=edge_q(outlet(1),:).*mesh.edge_length(outlet(1));
assert(max(abs(gauge_q-reference_q),[],'all')<=1e-12 && ...
    abs(trapz(native_time,gauge_q)-trapz(native_time,reference_q))<=1e-10, ...
    'HydroPol2D:VoronoiValidation','Gauge volume does not match its native edge flux.');

% A shared raster cell overlapped equally by two polygons must preserve
% volume. Alternating polygon peaks prove that maxima must follow remapping.
W=[0.5 0.5]; polygon_area=[50;50]; raster_area=100;
face_values=[2;4]; remapped=W*face_values;
assert(abs(remapped*raster_area-sum(face_values.*polygon_area))<=1e-12);
alternating=[10 0;0 10];
correct_max=max(W*alternating,[],2); incorrect_max=W*max(alternating,[],2);
assert(abs(correct_max-5)<=1e-12 && abs(incorrect_max-10)<=1e-12);

Summary=struct2table(results.summary);
Summary.hydrology_enabled=true;
Summary.groundwater_enabled=true;
Summary.required_netcdf_states_present=true;
Summary.geotiff_count=numel(results.raster_files);
Summary.figure_present=true;
Summary.video_present=true;
Summary.two_polygon_remap_conservative=true;
Summary.maximum_after_remap_verified=true;
Summary.gauge_flux_volume_verified=true;
writetable(Summary,fullfile(output_directory,'vtilted-end-to-end-validation-summary.csv'));
disp(Summary);
end
