function summary = run_mesh_editor_shared_acceptance(mesh_file, overlap_file, output_directory)
%RUN_MESH_EDITOR_SHARED_ACCEPTANCE Consume the Studio-edited mesh without rebuilding it.

arguments
    mesh_file (1,:) char
    overlap_file (1,:) char
    output_directory (1,:) char
end
if exist(output_directory, 'dir') ~= 7, mkdir(output_directory); end
contract = HydroPol2D_Validate_Mesh_Bundle(mesh_file, overlap_file);
mesh = HydroPol2D_Read_UGRID(mesh_file);
output_file = fullfile(output_directory, 'matlab_results.nc');
config = struct( ...
    'duration_s', 30, ...
    'initial_surface_depth_m', 0.02, ...
    'surface_roughness', 0.04, ...
    'min_dt_s', 0.0001, ...
    'max_dt_s', 1, ...
    'output_interval_s', 10, ...
    'courant', 0.2, ...
    'output_netcdf', output_file, ...
    'overwrite_output', true);
forcing = struct('overlap_file', overlap_file);
results = HydroPol2D_Voronoi_Run(mesh_file, config, forcing);

initial_storage = sum(mesh.surface_area) * config.initial_surface_depth_m;
final_storage = sum(results.final_surface_volume_m3) + sum(results.final_channel_volume_m3);
relative_error = abs(final_storage - initial_storage) / max(initial_storage, eps);
assert(relative_error <= 1e-9, 'HydroPol2D:MeshEditorAcceptanceMass', ...
    'MATLAB relative mass error %.3g exceeds 1e-9.', relative_error);

raw_neighbor = mesh.edge_neighbor(:) - 1;
summary = struct();
summary.mesh_path = mesh_file;
summary.overlap_path = overlap_file;
summary.matlab_archive = output_file;
summary.bundle_cells = contract.n_cells;
summary.bundle_faces = contract.n_faces;
summary.initial_storage_m3 = initial_storage;
summary.final_storage_m3 = final_storage;
summary.relative_mass_error = relative_error;
summary.topology = struct( ...
    'n_cells', mesh.n_cells, ...
    'n_edges', mesh.n_edges, ...
    'n_internal_edges', sum(raw_neighbor >= 0), ...
    'n_boundary_edges', sum(raw_neighbor < 0), ...
    'area_sum_m2', sum(mesh.cell_area), ...
    'edge_owner_zero_based', reshape(mesh.edge_owner(:) - 1, 1, []), ...
    'edge_neighbor_zero_based', reshape(raw_neighbor, 1, []));

summary_path = fullfile(output_directory, 'matlab_summary.json');
file_id = fopen(summary_path, 'w');
assert(file_id >= 0, 'HydroPol2D:MeshEditorAcceptanceOutput', ...
    'Could not create %s.', summary_path);
cleanup = onCleanup(@() fclose(file_id));
fwrite(file_id, jsonencode(summary, PrettyPrint=true), 'char');
fprintf('Mesh-editor shared acceptance passed: %d cells, %d edges, mass error %.3g.\n', ...
    mesh.n_cells, mesh.n_edges, relative_error);
end
