function [mesh, report] = HydroPol2D_Voronoi_Preflight(mesh_file, config)
%HYDROPOL2D_VORONOI_PREFLIGHT Fail early on invalid or unaffordable meshes.

allow_legacy = isfield(config, 'allow_legacy_mesh') && logical(config.allow_legacy_mesh);
mesh = HydroPol2D_Read_UGRID(mesh_file, allow_legacy=allow_legacy);
if isfield(config, 'compute_backend') && ~strcmpi(config.compute_backend, 'cpu')
    error('HydroPol2D:VoronoiGPUNotValidated', ...
        'Voronoi GPU execution is gated until CPU validation and a no-host-transfer GPU kernel pass.');
end
if mesh.channel.n_nodes > 0 && (~isfield(config, 'routing_solver') || ~strcmpi(config.routing_solver, 'local_inertial'))
    error('HydroPol2D:VoronoiChannelSolverUnavailable', ...
        'Unresolved channel graphs currently require routing_solver=local_inertial.');
end

internal = mesh.edge_neighbor > 0;
pairs = sort([mesh.edge_owner(internal), mesh.edge_neighbor(internal)], 2);
assert(size(unique(pairs, 'rows'),1) == size(pairs,1), ...
    'HydroPol2D:InvalidMesh', 'Duplicate internal owner-neighbour edges detected.');
assert(all(isfinite(mesh.cell_bed) & isfinite(mesh.surface_bed)), ...
    'HydroPol2D:InvalidMesh', 'Cell elevations must be finite.');

target_ratio = max(mesh.cell_target_width(mesh.edge_owner(internal)), ...
    mesh.cell_target_width(mesh.edge_neighbor(internal))) ./ ...
    min(mesh.cell_target_width(mesh.edge_owner(internal)), ...
    mesh.cell_target_width(mesh.edge_neighbor(internal)));
maximum_target_ratio = max(target_ratio, [], 'omitnan');
if isempty(maximum_target_ratio), maximum_target_ratio = 1; end
if isfield(config, 'maximum_adjacent_size_ratio')
    assert(maximum_target_ratio <= config.maximum_adjacent_size_ratio * (1 + 1e-10), ...
        'HydroPol2D:InvalidMesh', 'Adjacent mesh targets exceed the configured size ratio.');
end

cfl_width = mesh.cell_cfl_width(:);
if isfield(config, 'minimum_cell_width_m')
    assert(min(cfl_width) >= config.minimum_cell_width_m * (1 - 1e-8), ...
        'HydroPol2D:InvalidMesh', 'A CFL-relevant cell width is below the configured hard minimum.');
end

if mesh.channel.n_nodes > 0
    assert(all(isfinite(mesh.channel.bed) & isfinite(mesh.channel.bank)), ...
        'HydroPol2D:InvalidChannelGraph', 'Channel bed and bank elevations must be finite.');
    assert(~any(isfinite(mesh.cell_roughness(mesh.channel.host_cell))), ...
        'HydroPol2D:OverlappingChannelRepresentations', ...
        'A host polygon contains both resolved 2D bathymetry and subgrid storage.');
end

% Conservative upper estimate for double-precision state and work arrays.
state_values = 16 * mesh.n_cells + 10 * mesh.n_edges + ...
    12 * mesh.channel.n_nodes + 10 * mesh.channel.n_links + 8 * mesh.channel.n_transitions;
estimated_memory_bytes = 8 * state_values;
if isfield(config, 'available_memory_bytes') && isfinite(config.available_memory_bytes)
    assert(estimated_memory_bytes <= 0.70 * config.available_memory_bytes, ...
        'HydroPol2D:VoronoiMemoryGate', ...
        'Estimated state memory exceeds 70%% of available memory.');
end

report = struct('n_cells',mesh.n_cells,'n_edges',mesh.n_edges, ...
    'n_channel_nodes',mesh.channel.n_nodes,'n_channel_links',mesh.channel.n_links, ...
    'n_transitions',mesh.channel.n_transitions, ...
    'minimum_cfl_width_m',min(cfl_width), ...
    'maximum_adjacent_target_ratio',maximum_target_ratio, ...
    'estimated_memory_bytes_double',estimated_memory_bytes);
end
