%% ================================================================
% NON-BREAKING WAVE BENCHMARK GENERATOR FOR HYDROPOL2D
%
% Based on analytical diffusive-wave solution:
% h(x,t) = [ -(7/3) n^2 u^2 (x - u t) ]^(3/7)
%
% Boundary condition at x = 0:
% h(0,t) = [ (7/3) n^2 u^3 t ]^(3/7)
%
% Reference case:
%   32 x 240 cells
%   dx = 25 m
%   n  = 0.005 s/m^(1/3)
%   u  = 0.635 m/s
%
% This benchmark is the one used for the non-breaking wave validation
% in the HydroPol2D local-inertial paper.
% ================================================================

clear; clc; close all;

%% ================= USER PARAMETERS =================

outDir = '/oak/stanford/groups/gorelick/HydroPol2D/Case_Studies/NonBreakingWave/Static';

if ~exist(outDir, 'dir')
    mkdir(outDir);
end

dx = 25;              % grid resolution [m]

nx = 240;             % number of columns
ny = 32;              % number of rows

Lx = nx * dx;         % domain length [m]
Ly = ny * dx;         % domain width [m]

n_manning = 0.02;    % Manning roughness [s/m^(1/3)]
u_wave    = 1;    % analytical wave velocity [m/s]

z0 = 0;               % flat bed elevation [m]

compare_times_sec = [12 24 36 48]*60;

%% Uniform properties
DTB_val = 1;
Albedo_val = 0.5;
LAI_val = 0.5;
InitialSoilMoisture_val = 0;  % [mm]
GWdepth_val = 1;

%% ================= DOMAIN =================

[X, Y] = meshgrid(1:nx, 1:ny);

x = (X-1) * dx;
y = (Y-1) * dx; %#ok<NASGU>

x_profile = ((0:nx-1)' * dx);

%% ================= DEM =================

DEM = z0 * ones(ny,nx);

%% ================= INITIAL CONDITIONS =================

% This test starts dry.
% The wave is generated by a prescribed upstream stage boundary.
Initial_Depth_m = zeros(ny,nx);       % [m]
Initial_WSE     = DEM + Initial_Depth_m;

% HydroPol2D warmup depth in mm
Warmup_Depth = Initial_Depth_m * 1000; % [mm]

%% ================= UNIFORM RASTERS =================

LULC = ones(ny,nx);
SOIL = ones(ny,nx);

DTB        = DTB_val    * ones(ny,nx);
Albedo     = Albedo_val * ones(ny,nx);
LAI        = LAI_val    * ones(ny,nx);
GW_depth   = GWdepth_val * ones(ny,nx);

Initial_Soil_Moisture = InitialSoilMoisture_val * ones(ny,nx); % [mm]

GW_table = DEM - DTB + GW_depth;

%% ================= ANALYTICAL SOLUTION =================

Analytical = table();
Analytical.x_m = x_profile;

for it = 1:numel(compare_times_sec)

    t = compare_times_sec(it);

    h = analytical_nonbreaking_depth(x_profile, t, n_manning, u_wave);

    Analytical.(sprintf('h_t%05ds_m', t)) = h;
end

writetable(Analytical, fullfile(outDir,'NonBreakingWave_Analytical_Profiles.csv'));

%% ================= BOUNDARY STAGE HYDROGRAPH =================
% This is the stage/depth boundary condition that must be imposed
% at the first column of the model domain.

t_boundary_sec = (0:60:max(compare_times_sec))';

h_boundary_m = ((7/3) * n_manning^2 * u_wave^3 .* t_boundary_sec).^(3/7);
h_boundary_m(t_boundary_sec == 0) = 0;

Boundary_Hydrograph = table();
Boundary_Hydrograph.Time_sec = t_boundary_sec;
Boundary_Hydrograph.Time_min = t_boundary_sec / 60;
Boundary_Hydrograph.Depth_m  = h_boundary_m;
Boundary_Hydrograph.Depth_mm = h_boundary_m * 1000;
Boundary_Hydrograph.WSE_m    = z0 + h_boundary_m;

writetable(Boundary_Hydrograph, fullfile(outDir,'NonBreakingWave_Upstream_Stage_BC.csv'));

%% ================= SAFETY CHECK =================

rasterNames = {'DEM','LULC','SOIL','DTB','Albedo','LAI', ...
               'GW_table','Warmup_Depth','Initial_Soil_Moisture', ...
               'Initial_Depth_m','Initial_WSE'};

for k = 1:numel(rasterNames)
    A = eval(rasterNames{k});
    if any(isnan(A(:)))
        error('%s contains NaN values.', rasterNames{k});
    end
    if any(isinf(A(:)))
        error('%s contains Inf values.', rasterNames{k});
    end
end

%% ================= GEOREFERENCE =================

x0 = 0;
y0 = Ly;

R = maprefcells( ...
    [x0, x0 + nx*dx], ...
    [y0 - ny*dx, y0], ...
    [ny, nx], ...
    'ColumnsStartFrom','north');

epsgCode = 3857;

%% ================= WRITE GEOTIFF FILES =================

geotiffwrite(fullfile(outDir,'DEM.tif'),                   single(DEM),                   R, 'CoordRefSysCode', epsgCode);
geotiffwrite(fullfile(outDir,'LULC.tif'),                  single(LULC),                  R, 'CoordRefSysCode', epsgCode);
geotiffwrite(fullfile(outDir,'SOIL.tif'),                  single(SOIL),                  R, 'CoordRefSysCode', epsgCode);
geotiffwrite(fullfile(outDir,'DTB.tif'),                   single(DTB),                   R, 'CoordRefSysCode', epsgCode);
geotiffwrite(fullfile(outDir,'Albedo.tif'),                single(Albedo),                R, 'CoordRefSysCode', epsgCode);
geotiffwrite(fullfile(outDir,'LAI.tif'),                   single(LAI),                   R, 'CoordRefSysCode', epsgCode);
geotiffwrite(fullfile(outDir,'GW_table.tif'),              single(GW_table),              R, 'CoordRefSysCode', epsgCode);

geotiffwrite(fullfile(outDir,'Warmup_Depth.tif'),          single(Warmup_Depth),          R, 'CoordRefSysCode', epsgCode);
geotiffwrite(fullfile(outDir,'Initial_Soil_Moisture.tif'), single(Initial_Soil_Moisture), R, 'CoordRefSysCode', epsgCode);

% Optional diagnostic rasters
geotiffwrite(fullfile(outDir,'Initial_Depth_m.tif'),       single(Initial_Depth_m),       R, 'CoordRefSysCode', epsgCode);
geotiffwrite(fullfile(outDir,'Initial_WSE.tif'),           single(Initial_WSE),           R, 'CoordRefSysCode', epsgCode);

%% ================= PLOTTING =================

figure('Color','w','Position',[100 100 1500 750]);

subplot(2,2,1)
imagesc(DEM); axis image off; colorbar
title('Flat DEM [m]')

subplot(2,2,2)
imagesc(LULC); axis image off; colorbar
title('Uniform LULC')

subplot(2,2,3)
plot(Boundary_Hydrograph.Time_sec, Boundary_Hydrograph.Depth_m, ...
    'k-', 'LineWidth', 2)
grid on; box on
xlabel('Time [s]')
ylabel('Boundary depth h(0,t) [m]')
title('Upstream stage boundary condition')

subplot(2,2,4)
hold on
for it = 1:numel(compare_times_sec)
    t = compare_times_sec(it);
    plot(x_profile, Analytical.(sprintf('h_t%05ds_m',t)), ...
        'LineWidth', 2);
end
grid on; box on
xlabel('x [m]')
ylabel('Water depth h(x,t) [m]')
title('Analytical non-breaking wave profiles')
legend(compose('t = %d s', compare_times_sec), 'Location','best')

sgtitle('Non-Breaking Wave Benchmark')

exportgraphics(gcf, fullfile(outDir,'overview_nonbreaking_wave.png'), 'Resolution',300);

%% ================= COMMAND WINDOW SUMMARY =================

fprintf('\n============================================================\n');
fprintf('Non-breaking wave benchmark rasters saved to:\n%s\n', outDir);
fprintf('Domain: %d rows x %d cols\n', ny, nx);
fprintf('Cell size: %.2f m\n', dx);
fprintf('Length: %.2f m | Width: %.2f m\n', Lx, Ly);
fprintf('Manning n: %.4f s/m^(1/3)\n', n_manning);
fprintf('Wave velocity u: %.3f m/s\n', u_wave);
fprintf('Analytical profiles saved to:\n%s\n', fullfile(outDir,'NonBreakingWave_Analytical_Profiles.csv'));
fprintf('Boundary stage hydrograph saved to:\n%s\n', fullfile(outDir,'NonBreakingWave_Upstream_Stage_BC.csv'));
fprintf('Overview figure saved to:\n%s\n', fullfile(outDir,'overview_nonbreaking_wave.png'));
fprintf('============================================================\n\n');

%% ================================================================
% LOCAL FUNCTION
% ================================================================

function h = analytical_nonbreaking_depth(x, t, n, u)

    arg = -(7/3) * n^2 * u^2 .* (x - u*t);

    h = zeros(size(x));

    wet = arg > 0;

    h(wet) = arg(wet).^(3/7);

    h(~isfinite(h)) = 0;
    h(h < 0) = 0;
end