% P1-SNOW-001 full-model V-tilted configuration.
% The parent validation runner supplies InputPaths, including the generated
% station meteorological forcing workbook.

if ~exist('InputPaths', 'var') || ~isstruct(InputPaths)
    error('P1-SNOW-001 requires InputPaths from the full-model validation runner.');
end

InputData_Bypass = struct();

G = struct();
G.time_step_model = 15;                 % min
G.min_time_step = 1;                    % s
G.max_time_step = 900;                  % s
G.time_step_increments = 0.001;
G.time_step_change = 0.0001;
G.alfa_min = 0.50;
G.alfa_max = 0.50;
G.date_begin = datetime(2025, 1, 30, 0, 0, 0);
G.date_end = datetime(2025, 1, 30, 2, 15, 0);
G.routing_time = 135;                   % min
G.etp_input_spreadsheet = InputPaths.ETP_input_spreadsheet;
G.slope_outlet = 0.02;
G.n_outlets_data = 1;
G.record_time_maps = 15;
G.record_time_hydrographs = 15;
G.record_time_spatial_rainfall = 15;
G.time_save_ETP = 60;
G.record_time_spatial_ETP = 60;
G.Pol_min = 0.001;
G.depth_wse = 0.01;
G.flag_wse = 0;
G.Krs_ETP = 0.13;
G.albedo = 0.80;
G.volume_error = 1e6;
G.factor_reduction = 2;
G.CA_depth_tolerance = 1e-4;
G.alfa_1 = 1;
G.alfa_2 = 1;
G.beta_1 = 1;
G.beta_2 = 1;
G.Manning = 0.04;
G.River_K_coeff = 1;
G.ADD = 0;
G.min_Bt = 0;
G.Bmin = 0;
G.Bmax = 0;
G.min_area = 1e-4;
G.tau = 0;
G.K_value = 0;
G.sl = 0;
G.slope_DTM = 0;
G.RP = 1;
G.Rainfall_Duration = 60;
G.K = 1;
G.a = 1;
G.b = 1;
G.c = 1;
G.dt_design = 15;
InputData_Bypass.general = G;

flag_names = { ...
    'flag_rainfall','flag_spatial_rainfall','flag_ETP','flag_input_rainfall_map', ...
    'flag_rainfall_multiple_runs','flag_data_source','flag_inflow','flag_satellite_rainfall', ...
    'flag_alternated_blocks','flag_huff','flag_stage_hydrograph','flag_input_ETP_map', ...
    'flag_timestep','flag_infiltration','flag_critical','flag_D8','flag_CA','flag_inertial', ...
    'flag_full_momentum','flag_waterbalance','flag_waterquality','flag_reservoir','flag_wq_model', ...
    'flag_groundwater_modeling','flag_real_time_satellite_rainfall','flag_dam_break', ...
    'flag_human_instability','flag_boundary','flag_numerical_scheme','flag_outlet_type', ...
    'flag_adaptive_timestepping','flag_neglect_infiltration_river','flag_subgrid', ...
    'flag_spatial_albedo','flag_river_rasters','flag_baseflow','flag_kinematic', ...
    'flag_diffusive','flag_DTM','flag_abstraction','flag_overbanks','flag_snow_modeling', ...
    'flag_WQ_Rasters','flag_GPU','flag_single','flag_warmup','flag_initial_buildup', ...
    'flag_resample','flag_smoothening','flag_trunk','flag_fill_DEM','flag_smooth_cells', ...
    'flag_reduce_DEM','flag_export_maps','flag_river_heigth_compensation', ...
    'flag_dashboard','flag_elapsed_time','flag_obs_gauges'};
InputData_Bypass.flags = cell2struct(num2cell(zeros(numel(flag_names), 1)), flag_names, 1);
InputData_Bypass.flags.flag_rainfall = 1;
InputData_Bypass.flags.flag_ETP = 1;
InputData_Bypass.flags.flag_timestep = 1;
InputData_Bypass.flags.flag_infiltration = 1;
InputData_Bypass.flags.flag_inertial = 1;
InputData_Bypass.flags.flag_numerical_scheme = 1;
InputData_Bypass.flags.flag_outlet_type = 1;
InputData_Bypass.flags.flag_adaptive_timestepping = 1;
InputData_Bypass.flags.flag_snow_modeling = 1;
InputData_Bypass.flags.flag_warmup = 1;
InputData_Bypass.flags.flag_export_maps = 0;

LULC = table({'V-tilted class 1'; 'V-tilted class 2'; 'V-tilted class 3'}, ...
    [1; 2; 3], [0.060; 0.040; 0.075], zeros(3,1), zeros(3,1), ...
    zeros(3,1), zeros(3,1), zeros(3,1), zeros(3,1), [NaN; NaN; NaN], ...
    [0.30; 0.15; 0.25], [0.80; 0.60; 0.75], 0.98 * ones(3,1), ...
    zeros(3,1), [2; 4; 3], [-1; 1; 0], [1; 3; 2], [100; 200; 150], ...
    [450; 500; 475], zeros(3,1), zeros(3,1), zeros(3,1), ...
    'VariableNames', {'LULC','Index','roughness','h_0_mm','d_0_mm','C1','C2','C3','C4', ...
    'index_impervious','root_depth_m','Snow_Albedo','Snow_Emissivity', ...
    'Sublimation_Coefficient_d_1','Degree_Day_Factor_mm_C_day','T_Snow_All_C', ...
    'T_Rain_All_C','Rho_Snow_Init_kg_m3','Rho_Snow_Max_kg_m3', ...
    'Compaction_Temperature_kg_m3_C_day','Compaction_SWE_kg_m3_mm_day', ...
    'Compaction_Depth_kg_m3_mm_day'});
InputData_Bypass.LULC = struct('table', LULC);

SOIL = table({'V-tilted soil 1'; 'V-tilted soil 2'; 'V-tilted soil 3'}, ...
    [1; 2; 3], [0.001; 0.001; 0.001], 1.6 * ones(3,1), ...
    2.0 * ones(3,1), 0.45 * ones(3,1), 0.05 * ones(3,1), ...
    0.20 * ones(3,1), 0.20 * ones(3,1), 0.001 * ones(3,1), ...
    1.0 * ones(3,1), ones(3,1), ones(3,1), ones(3,1), ...
    0.10 * ones(3,1), 0.25 * ones(3,1), 0.50 * ones(3,1), ...
    'VariableNames', {'Soil_type','Index','ksat_mm_h','n_vg','alpha_vg_1_m','theta_sat', ...
    'theta_r','theta_i','Sy','ksat_gw_mm_h','Soil_Depth_m', ...
    'Ks_multiplier_near_surface','Ks_multiplier_root_zone', ...
    'Ks_multiplier_transmission','Ltop_m','dh_max_m','l_vg'});
InputData_Bypass.SOIL = struct('table', SOIL);

InputData_Bypass.Rainfall_Parameters = struct( ...
    'time_rainfall', (0:15:135)', ...
    'intensity_rainfall', [10; 10; 10; 10; 10; 0; 0; 0; 0; 0], ...
    'time_step_rainfall', 15, ...
    'rainfall_duration', 60, ...
    'n_obs_rainfall', 10);
