% Canonical V-Tilted inputs: 10.8 mm/h for 90 min, simulated for 180 min.
config_root = fileparts(mfilename('fullpath'));
case_root = fileparts(config_root);
mesh_mode = lower(strtrim(getenv('HYDROPOL_VTILTED_MESH')));
if isempty(mesh_mode), mesh_mode = 'regular'; end
if ~ismember(mesh_mode, {'regular', 'voronoi'})
    error('HydroPol2D:VTiltedMeshMode', ...
        'HYDROPOL_VTILTED_MESH must be regular or voronoi.');
end

InputData_Bypass = struct();
InputData_Bypass.general = struct( ...
    'time_step_model', 1/60, ...
    'min_time_step', 0.01, ...
    'max_time_step', 1, ...
    'time_step_increments', 0.001, ...
    'time_step_change', 0.001, ...
    'alfa_min', 0.5, ...
    'alfa_max', 0.5, ...
    'date_begin', datetime(2025,5,1,0,0,0), ...
    'date_end', datetime(2025,5,1,3,0,0), ...
    'slope_outlet', 0.004, ...
    'n_outlets_data', 3, ...
    'record_time_maps', 1, ...
    'record_time_hydrographs', 1, ...
    'Pol_min', 0.001, ...
    'depth_wse', 0.01, ...
    'flag_wse', 0, ...
    'record_time_spatial_rainfall', 10, ...
    'time_save_ETP', 60, ...
    'record_time_spatial_ETP', 60, ...
    'alfa_1', 0.1097, ...
    'alfa_2', 0.3856, ...
    'beta_1', 2.2695, ...
    'beta_2', 0.4942, ...
    'Manning', 0.04, ...
    'ADD', 10, ...
    'min_Bt', 0.01, ...
    'Bmin', 0.01, ...
    'Bmax', 100, ...
    'min_area', 25, ...
    'tau', 0.2, ...
    'K_value', 10, ...
    'sl', 1e-4, ...
    'slope_DTM', 5, ...
    'RP', 100, ...
    'Rainfall_Duration', 90, ...
    'K', 868.9, ...
    'a', 0.193, ...
    'b', 7.662, ...
    'c', 0.701, ...
    'dt_design', 15);

flag_names = { ...
    'flag_spatial_rainfall','flag_ETP','flag_input_rainfall_map', ...
    'flag_rainfall_multiple_runs','flag_data_source','flag_inflow', ...
    'flag_satellite_rainfall','flag_alternated_blocks','flag_huff', ...
    'flag_stage_hydrograph','flag_input_ETP_map','flag_infiltration', ...
    'flag_D8','flag_CA','flag_full_momentum','flag_waterquality', ...
    'flag_reservoir','flag_wq_model','flag_groundwater_modeling', ...
    'flag_real_time_satellite_rainfall','flag_dam_break', ...
    'flag_human_instability','flag_boundary','flag_neglect_infiltration_river', ...
    'flag_neal_channel','flag_structured_lookup_subgrid','flag_voronoi_subgrid', ...
    'flag_spatial_albedo','flag_river_rasters','flag_baseflow','flag_kinematic', ...
    'flag_diffusive','flag_DTM','flag_abstraction','flag_snow_modeling', ...
    'flag_WQ_Rasters','flag_GPU','flag_warmup','flag_initial_buildup', ...
    'flag_resample','flag_smoothening','flag_trunk','flag_fill_DEM', ...
    'flag_smooth_cells','flag_reduce_DEM','flag_river_heigth_compensation', ...
    'flag_dashboard','flag_elapsed_time','flag_obs_gauges'};
flags = cell2struct(num2cell(zeros(size(flag_names))), flag_names, 2);
flags.flag_rainfall = 1;
flags.flag_timestep = 1;
flags.flag_critical = 1;
flags.flag_inertial = 1;
flags.flag_waterbalance = 1;
flags.flag_numerical_scheme = 1;
flags.flag_outlet_type = 1;
flags.flag_adaptive_timestepping = 1;
flags.flag_single = 1;
flags.flag_export_maps = 1;
flags.flag_voronoi = double(strcmp(mesh_mode, 'voronoi'));
InputData_Bypass.flags = flags;

InputData_Bypass.LULC = struct( ...
    'names', {{'Validation surface'}}, ...
    'index', 1, ...
    'parameters', [0.04, 0, 0, 0, 0, 0, 0, NaN, 1, 1], ...
    'impervious_index', NaN);
InputData_Bypass.SOIL = struct( ...
    'names', {{'Validation soil'}}, ...
    'index', 1, ...
    'parameters', [18, 1.56, 3.6, 0.45, 0.05, 0.19, 0.2, 18, 1, 1, 1, 1, 0.05, 1, 0.5]);
InputData_Bypass.Rainfall_Parameters = struct( ...
    'time_rainfall', [90; 180], ...
    'intensity_rainfall', [10.8; 0]);

InputData_Bypass.Voronoi = struct( ...
    'case_file', fullfile(case_root, 'Prepared_Cases', ...
        'vtilted-standard-uniform20-case.mat'), ...
    'background_target_width_m', 20, ...
    'minimum_cell_width_m', 20, ...
    'maximum_adjacent_size_ratio', 1, ...
    'urban_target_width_m', 20, ...
    'urban_transition_buffer_m', 0, ...
    'unresolved_river_policy', 'none');
InputData_Bypass.VoronoiOutput = struct( ...
    'write_native_archive', true, ...
    'native_output_interval_s', 60, ...
    'write_final_geotiffs', true, ...
    'write_temporal_geotiffs', false, ...
    'raster_stack_interval_s', 900, ...
    'write_figures', true, ...
    'write_videos', false, ...
    'write_gauge_hydrographs', true);
