function case_file = prepare_standard_case()
%PREPARE_STANDARD_CASE Build the canonical 10.8 mm/h V-tilted Excel fixture.

example_root = fileparts(mfilename('fullpath'));
model_root = fileparts(fileparts(example_root));
static_dir = fullfile(example_root,'Static');
case_dir = fullfile(example_root,'Prepared_Cases');
if ~exist(static_dir,'dir'), mkdir(static_dir); end
if ~exist(case_dir,'dir'), mkdir(case_dir); end

addpath(fullfile(model_root,'HydroPol2D_Functions'));

dx = 20;
nx = 41;
ny = 31;
side_slope = 0.02;
outlet_slope = 0.004;
[column,row] = meshgrid(1:nx,1:ny);
center = ceil(nx/2);
dem = side_slope .* abs(column-center) .* dx + ...
    outlet_slope .* (ny-row) .* dx;

R = maprefcells([0,nx*dx],[0,ny*dx],[ny,nx], ...
    'ColumnsStartFrom','north');
write_raster('DEM.tif',single(dem));
write_raster('LULC.tif',ones(ny,nx,'single'));
write_raster('SOIL.tif',ones(ny,nx,'single'));
write_raster('DTB.tif',ones(ny,nx,'single'));
write_raster('Initial_SM.tif',zeros(ny,nx,'single'));
write_raster('Albedo.tif',0.23*ones(ny,nx,'single'));
write_raster('LAI.tif',zeros(ny,nx,'single'));

mesh_relative = fullfile('Validation','Voronoi','fixtures_vtilted_20m', ...
    'vtilted-uniform20-mesh.nc');
overlap_relative = fullfile('Validation','Voronoi','fixtures_vtilted_20m', ...
    'vtilted-uniform20-overlap.nc');
mesh_file = fullfile(model_root,mesh_relative);
mesh = HydroPol2D_Read_UGRID(mesh_file);
outlet = find(mesh.edge_neighbor == 0 & abs(mesh.edge_midpoint_y) < 1e-8 & ...
    mesh.edge_midpoint_x >= 380 & mesh.edge_midpoint_x <= 440);
assert(abs(sum(mesh.edge_length(outlet))-60) <= 1e-8, ...
    'HydroPol2D:VTiltedFixture','V-tilted outlet width must be 60 m.');

rainfall_rate_m_s = 10.8e-3/3600;
storm_duration_s = 90*60;
simulation_duration_s = 180*60;
config = struct( ...
    'duration_s',simulation_duration_s, ...
    'min_dt_s',0.01, ...
    'max_dt_s',1, ...
    'output_interval_s',60, ...
    'forcing_interval_s',inf, ...
    'courant',0.2, ...
    'surface_roughness',0.04, ...
    'critical_flow',true, ...
    'compute_backend','cpu');
forcing = struct( ...
    'surface_source_m_s',@(time_s,~,~) rainfall_rate_m_s .* double(time_s < storm_duration_s), ...
    'surface_boundary',struct( ...
        'edge_id',outlet,'type',"normal_flow",'value',outlet_slope));
options = struct( ...
    'background_target_width_m',20, ...
    'minimum_cell_width_m',20, ...
    'maximum_adjacent_size_ratio',1, ...
    'urban_target_width_m',20, ...
    'urban_transition_buffer_m',0, ...
    'unresolved_river_policy','none');

VoronoiCase = struct( ...
    'mesh_file',mesh_relative, ...
    'overlap_file',overlap_relative, ...
    'config',config, ...
    'forcing',forcing, ...
    'options',options, ...
    'output_prefix','vtilted-standard-uniform20', ...
    'expected_input_volume_m3',rainfall_rate_m_s*storm_duration_s*sum(mesh.cell_area), ...
    'maximum_input_volume_error_fraction',1e-10, ...
    'maximum_mass_residual_fraction',1e-3);
VoronoiCase.output_controls = struct( ...
    'write_native_archive',true, ...
    'native_output_interval_s',60, ...
    'write_final_geotiffs',true, ...
    'write_temporal_geotiffs',false, ...
    'raster_stack_interval_s',900, ...
    'write_figures',true, ...
    'write_videos',false, ...
    'write_gauge_hydrographs',true);

case_file = fullfile(case_dir,'vtilted-standard-uniform20-case.mat');
save(case_file,'VoronoiCase');

    function write_raster(name,A)
        geotiffwrite(fullfile(static_dir,name),A,R,'CoordRefSysCode',3857);
    end
end
