function results = run_pune_voronoi_100mm_12h(mesh_case, output_case, mesh_options, minimum_timestep_s, run_options)
%RUN_PUNE_VORONOI_100MM_12H Pune adaptive-mesh routing smoke test.
%
% Uniform rainfall is 100 mm/h for the first hour and zero for the
% following 11 hours. Surface routing uses the CPU local-inertial solver.

if nargin < 1 || isempty(mesh_case)
    mesh_case = 'pune_design_corridor_mesh_complete';
end
if nargin < 2 || isempty(output_case)
    output_case = '100mm_1h_12h';
end
default_mesh_options = struct( ...
    'background_target_width_m', 120, ...
    'minimum_cell_width_m', 15, ...
    'maximum_adjacent_size_ratio', 3, ...
    'urban_target_width_m', 45, ...
    'urban_transition_buffer_m', 300, ...
    'unresolved_river_policy', 'none');
if nargin < 3 || isempty(mesh_options)
    mesh_options = default_mesh_options;
else
    names = fieldnames(default_mesh_options);
    for k = 1:numel(names)
        if ~isfield(mesh_options, names{k}) || isempty(mesh_options.(names{k}))
            mesh_options.(names{k}) = default_mesh_options.(names{k});
        end
    end
end
if nargin < 4 || isempty(minimum_timestep_s)
    minimum_timestep_s = 0.05;
end
default_run_options = struct( ...
    'duration_s', 12 * 3600, ...
    'rainfall_intensity_mm_h', 100, ...
    'rainfall_duration_s', 3600, ...
    'output_interval_s', 3600, ...
    'forcing_interval_s', 3600, ...
    'raster_output_interval_s', 3600, ...
    'courant', 0.2, ...
    'max_dt_s', 30, ...
    'progress_interval_s', 300, ...
    'boundary_type', 'normal_flow', ...
    'boundary_value', 0.01, ...
    'critical_flow_limiter', true, ...
    'write_native_archive', true, ...
    'write_final_geotiffs', true, ...
    'write_temporal_geotiffs', true, ...
    'write_figures', true, ...
    'write_videos', true, ...
    'write_gauge_hydrographs', true, ...
    'mesh_file', '', ...
    'overlap_file', '', ...
    'subgrid_table_path', '', ...
    'outlet_edge_ids_0based', [], ...
    'outlet_search_radius_m', 240);
if nargin < 5 || isempty(run_options)
    run_options = default_run_options;
else
    names = fieldnames(default_run_options);
    for k = 1:numel(names)
        if ~isfield(run_options, names{k}) || isempty(run_options.(names{k}))
            run_options.(names{k}) = default_run_options.(names{k});
        end
    end
end
assert(run_options.courant > 0 && run_options.courant <= 0.3, ...
    'HydroPol2D:InvalidVoronoiCourant', ...
    'Pune Voronoi Courant must be in (0, 0.3]; the validated default is 0.2.');

case_directory = fileparts(mfilename('fullpath'));
repository_root = fileparts(fileparts(case_directory));
mesh_file = fullfile(fileparts(repository_root), 'HydroBathyDEM', ...
    'examples', 'pune_catchment', 'outputs', ...
    mesh_case, 'mesh', 'hydropol_hybrid_mesh.nc');
overlap_file = fullfile(fileparts(repository_root), 'HydroBathyDEM', ...
    'examples', 'pune_catchment', 'outputs', ...
    mesh_case, 'mesh', 'hydropol_mesh_overlap.nc');
if strlength(strtrim(string(run_options.mesh_file))) > 0
    mesh_file = char(run_options.mesh_file);
end
if strlength(strtrim(string(run_options.overlap_file))) > 0
    overlap_file = char(run_options.overlap_file);
end
if strlength(strtrim(string(run_options.subgrid_table_path))) > 0
    mesh_options.subgrid_table_path = char(run_options.subgrid_table_path);
    mesh_options.voronoi_subgrid_enabled = true;
end
output_directory = fullfile(case_directory, 'Outputs', output_case);
if exist(output_directory, 'dir') ~= 7, mkdir(output_directory); end
output_prefix = ['pune-' output_case];
diary_file = fullfile(output_directory, [output_prefix '-run.log']);
diary(diary_file);
diary_cleanup = onCleanup(@() diary('off'));

addpath(fullfile(repository_root, 'HydroPol2D_Functions'));
mesh = HydroPol2D_Read_UGRID(mesh_file);

if ~isempty(run_options.outlet_edge_ids_0based)
    outlet_edges = double(run_options.outlet_edge_ids_0based(:)) + 1;
    assert(all(outlet_edges >= 1 & outlet_edges <= mesh.n_edges) && ...
        all(mesh.edge_neighbor(outlet_edges) == 0), ...
        'HydroPol2D:InvalidVoronoiBoundary', ...
        'outlet_edge_ids_0based must identify boundary faces in the UGRID file.');
else
    boundary_edges = find(mesh.edge_neighbor == 0);
    boundary_cells = mesh.edge_owner(boundary_edges);
    [~, lowest_index] = min(mesh.surface_bed(boundary_cells));
    outlet_cell = boundary_cells(lowest_index);
    outlet_distance = hypot(mesh.edge_midpoint_x(boundary_edges) - mesh.cell_x(outlet_cell), ...
        mesh.edge_midpoint_y(boundary_edges) - mesh.cell_y(outlet_cell));
    outlet_edges = boundary_edges(outlet_distance <= run_options.outlet_search_radius_m);
    if isempty(outlet_edges), outlet_edges = boundary_edges(lowest_index); end
end

config = struct( ...
    'routing_solver', 'local_inertial', ...
    'duration_s', run_options.duration_s, ...
    'min_dt_s', minimum_timestep_s, ...
    'max_dt_s', run_options.max_dt_s, ...
    'output_interval_s', run_options.output_interval_s, ...
    'forcing_interval_s', run_options.forcing_interval_s, ...
    'raster_output_interval_s', run_options.raster_output_interval_s, ...
    'courant', run_options.courant, ...
    'surface_roughness', 0.04, ...
    'critical_flow', run_options.critical_flow_limiter, ...
    'progress_interval_s', run_options.progress_interval_s, ...
    'progress_checkpoint_file', fullfile(output_directory, 'live_checkpoint.mat'), ...
    'hydrology_enabled', false, ...
    'groundwater_enabled', false);
forcing = struct( ...
    'surface_source_m_s', @(time_s, state, current_mesh) double(time_s < run_options.rainfall_duration_s) * ...
        run_options.rainfall_intensity_mm_h / 1000 / 3600, ...
    'surface_boundary', struct('edge_id', outlet_edges, ...
        'type', string(run_options.boundary_type), 'value', run_options.boundary_value));

case_definition = struct( ...
    'mesh_file', mesh_file, ...
    'overlap_file', overlap_file, ...
    'config', config, ...
    'forcing', forcing, ...
    'output_prefix', output_prefix, ...
    'expected_input_volume_m3', run_options.rainfall_intensity_mm_h / 1000 / 3600 * ...
        min(run_options.rainfall_duration_s, run_options.duration_s) * sum(mesh.cell_area), ...
    'options', mesh_options);
case_definition.output_controls = struct( ...
    'write_native_archive', run_options.write_native_archive, ...
    'native_output_interval_s', run_options.raster_output_interval_s, ...
    'write_final_geotiffs', run_options.write_final_geotiffs, ...
    'write_temporal_geotiffs', run_options.write_temporal_geotiffs, ...
    'raster_stack_interval_s', run_options.raster_output_interval_s, ...
    'write_figures', run_options.write_figures, ...
    'write_videos', run_options.write_videos, ...
    'write_gauge_hydrographs', run_options.write_gauge_hydrographs);

fprintf('Pune Voronoi event: %d cells, %d edges, %d outlet faces.\n', ...
    mesh.n_cells, mesh.n_edges, numel(outlet_edges));
fprintf('Rainfall: %.6g mm/h for %.3f h; routing duration: %.3f h; Courant: %.3f.\n', ...
    run_options.rainfall_intensity_mm_h, run_options.rainfall_duration_s / 3600, ...
    run_options.duration_s / 3600, run_options.courant);
results = HydroPol2D_Run_Voronoi_Case(case_definition, output_directory, true);
save(fullfile(output_directory, [output_prefix '-final-results.mat']), ...
    'results', '-v7.3');
disp(struct2table(results.summary));
end
