function Catalog = hydropol2d_default_parameter_catalog(baseOverrides)
%HYDROPOL2D_DEFAULT_PARAMETER_CATALOG Default calibratable HydroPol2D fields.
%
% Catalog is catchment-size agnostic: the actual LULC/SOIL class IDs are
% read from baseOverrides.LULC.Index and baseOverrides.SOIL.Index. If a new
% catchment has 2, 8, or 30 classes, the same catalog can generate the
% matching parameter specs.
%
% Each field rule can create:
%   1) one global multiplier across all active classes;
%   2) one direct value parameter per class.
%
% The first option is usually better for early calibration. The second is
% useful after sensitivity analysis or when observations can identify
% class-specific parameters.

if nargin < 1
    baseOverrides = struct();
end

Catalog = struct();
Catalog.LULC = struct();
Catalog.LULC.Index = get_index_or_empty(baseOverrides, 'LULC');
Catalog.LULC.Fields = [ ...
    field_rule('roughness', ...
        0.015, 0.20, 0.05, 'log', true, [0.50, 3.00, 1.00], ...
        'lulc_roughness_multiplier_all'); ...
    field_rule('root_depth_m', ...
        0.05, 2.50, 0.60, 'linear', true, [0.50, 2.00, 1.00], ...
        'lulc_root_depth_multiplier_all') ...
    ];

Catalog.SOIL = struct();
Catalog.SOIL.Index = get_index_or_empty(baseOverrides, 'SOIL');
Catalog.SOIL.Fields = [ ...
    field_rule('ksat_mm_h', ...
        0.05, 500.0, 10.0, 'log', true, [0.10, 10.0, 1.00], ...
        'soil_ksat_multiplier_all'); ...
    field_rule('n_vg', ...
        1.05, 4.00, 1.50, 'linear', false, [nan, nan, nan], ''); ...
    field_rule('alpha_vg_1_m', ...
        0.20, 50.0, 3.00, 'log', true, [0.20, 5.00, 1.00], ...
        'soil_alpha_vg_multiplier_all'); ...
    field_rule('theta_sat', ...
        0.25, 0.60, 0.40, 'linear', false, [nan, nan, nan], ''); ...
    field_rule('theta_r', ...
        0.01, 0.20, 0.06, 'linear', false, [nan, nan, nan], ''); ...
    field_rule('theta_i', ...
        0.02, 0.55, 0.12, 'linear', true, [0.50, 1.05, 1.00], ...
        'soil_theta_i_multiplier_all'); ...
    field_rule('Sy', ...
        0.01, 0.35, 0.15, 'linear', true, [0.25, 3.00, 1.00], ...
        'soil_specific_yield_multiplier_all'); ...
    field_rule('ksat_gw_mm_h', ...
        0.10, 10000.0, 100.0, 'log', true, [0.10, 10.0, 1.00], ...
        'soil_groundwater_ksat_multiplier_all'); ...
    field_rule('Soil_Depth_m', ...
        0.10, 5.00, 1.00, 'log', true, [0.30, 3.00, 1.00], ...
        'soil_depth_multiplier_all'); ...
    field_rule('Ks_multiplier_near_surface', ...
        0.01, 20.0, 1.00, 'log', true, [0.20, 8.00, 1.00], ...
        'soil_ks_near_surface_multiplier_all'); ...
    field_rule('Ks_multiplier_root_zone', ...
        0.01, 20.0, 1.00, 'log', true, [0.20, 8.00, 1.00], ...
        'soil_ks_root_zone_multiplier_all'); ...
    field_rule('Ks_multiplier_transmission', ...
        0.01, 20.0, 1.00, 'log', true, [0.20, 8.00, 1.00], ...
        'soil_ks_transmission_multiplier_all') ...
    ];

Catalog.InputData = [ ...
    input_rule('general_slope_outlet', 'general.slope_outlet', ...
        0.001, 0.10, 0.02, 'log') ...
    ];
end

function idx = get_index_or_empty(baseOverrides, group)
    idx = [];
    if isfield(baseOverrides, group) && isstruct(baseOverrides.(group)) && ...
            isfield(baseOverrides.(group), 'Index')
        idx = baseOverrides.(group).Index(:);
    end
end

function rule = field_rule(field, lower, upper, initialDefault, transform, ...
        makeGlobalMultiplier, multiplierBounds, globalName)
    rule = struct();
    rule.field = char(field);
    rule.lower = double(lower);
    rule.upper = double(upper);
    rule.initial_default = double(initialDefault);
    rule.transform = char(transform);
    rule.make_global_multiplier = logical(makeGlobalMultiplier);
    rule.multiplier_lower = double(multiplierBounds(1));
    rule.multiplier_upper = double(multiplierBounds(2));
    rule.multiplier_initial = double(multiplierBounds(3));
    rule.global_name = char(globalName);
    rule.make_class_values = true;
end

function rule = input_rule(name, path, lower, upper, initial, transform)
    rule = struct();
    rule.name = char(name);
    rule.path = char(path);
    rule.lower = double(lower);
    rule.upper = double(upper);
    rule.initial = double(initial);
    rule.transform = char(transform);
    rule.enabled = false;
end
