function s = hydropol2d_empty_parameter_spec()
%HYDROPOL2D_EMPTY_PARAMETER_SPEC Return the canonical parameter spec schema.

s = struct('name', '', ...
    'target', '', ...
    'field', '', ...
    'index', [], ...
    'path', '', ...
    'operation', 'value', ...
    'lower', nan, ...
    'upper', nan, ...
    'initial', nan, ...
    'transform', 'linear', ...
    'enabled', false, ...
    'lower_internal', nan, ...
    'upper_internal', nan, ...
    'initial_internal', nan);
end
