%RUN_EXCEL Run the portable Stanford 30 m example from Excel workbooks.

case_root = fileparts(mfilename('fullpath'));
model_root = fileparts(fileparts(case_root));
workbook = fullfile(case_root, 'Input_Data_Sheets', 'General_Data.xlsx');
required_files = { ...
    workbook, ...
    fullfile(case_root, 'Input_Data_Sheets', 'LULC_parameters.xlsx'), ...
    fullfile(case_root, 'Input_Data_Sheets', 'SOIL_parameters.xlsx'), ...
    fullfile(case_root, 'Input_Data_Sheets', 'Rainfall_Intensity_Data.xlsx'), ...
    fullfile(case_root, 'Static', 'DEM.tif'), ...
    fullfile(case_root, 'Static', 'LULC.tif'), ...
    fullfile(case_root, 'Static', 'SOIL.tif')};

for index = 1:numel(required_files)
    assert(isfile(required_files{index}), ...
        'Stanford input is missing: %s', required_files{index});
end

setenv('HYDROPOL_RUN_MODE', 'excel');
setenv('HYDROPOL_INPUT_EXCEL_FILE', workbook);
setenv('HYDROPOL_EXPORT_ROOT_DIR', ...
    fullfile(case_root, 'Outputs', 'Reruns_CurrentModel', 'Stanford_30m_Excel'));
setenv('HYDROPOL_SKIP_POSTPROCESS', '');

run(fullfile(model_root, 'HydroPol2D_V115.m'));
