%RUN_STANFORD_10M_LIDAR_24H
% Prepared command for the Stanford 10 m current-model website/design event.
% This script intentionally does not run during repository packaging; launch
% it from MATLAB when ready.

case_root = fileparts(mfilename('fullpath'));

run_stanford_local_case( ...
    'Resolution', 10, ...
    'StaticFolder', fullfile(case_root, 'Static_10m_LiDAR_ModelDEM'), ...
    'SimulationMinutes', 24 * 60, ...
    'RainfallTimeseriesPath', fullfile(case_root, 'Forcing', 'Rainfall', 'Rainfall_Intensity_Website_100mmh_1h_24h.csv'), ...
    'OutputTag', 'Stanford_10m_LiDAR_ModelDEM_Website_100mmh_1h_24h_PerimeterOutlet_ConfigAligned', ...
    'RunPostprocessing', false, ...
    'RecordTimeMapsMinutes', 15, ...
    'RecordTimeHydrographsMinutes', 15, ...
    'UseGPU', false, ...
    'UseSingle', false);
