function run_code(varargin)
%RUN_CODE Run the portable Stanford 30 m example from MATLAB configuration.

run_stanford_local_case( ...
    'Resolution', 30, ...
    'SimulationMinutes', 180, ...
    'RecordTimeMapsMinutes', 15, ...
    'RecordTimeHydrographsMinutes', 15, ...
    'OutputTag', 'Stanford_30m_Code', ...
    varargin{:});
end
